# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/197d34w_6DvDOXHAwvN-QjgItKBoKz8R3
"""

import pandas as pd

data = pd.read_csv('/content/house_prices.csv')

data

features = data.iloc[:,3:]

features

labels = data.iloc[:,2:3]

labels

missing = data.isnull().sum()

missing

features = pd.get_dummies(features)
features

labels = pd.get_dummies(labels)
labels

from sklearn.preprocessing import MinMaxScaler
scale = MinMaxScaler()
features = scale.fit_transform(features)
features

scale2 = MinMaxScaler()
labels = scale2.fit_transform(labels)
labels

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(features,labels,test_size=0.2)

x_train

x_test

y_train

y_test

print(len(features))

print(len(x_train))

print(len(x_test))

from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(x_train,y_train)

model.score(x_test,y_test)

import pickle
weights = pickle.dump(model,open('house_prices.sav','wb'))
weights